package com.chase.entity;
// default package
// Generated May 7, 2017 12:56:58 AM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

/**
 * Accounts generated by hbm2java
 */
public class Accounts implements java.io.Serializable {

	private BigDecimal accountNumber;
	private String owner;
	private Double balance;

	public Accounts() {
	}

	public Accounts(BigDecimal accountNumber) {
		this.accountNumber = accountNumber;
	}

	public Accounts(BigDecimal accountNumber, String owner, Double balance) {
		this.accountNumber = accountNumber;
		this.owner = owner;
		this.balance = balance;
	}

	public BigDecimal getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(BigDecimal accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public Double getBalance() {
		return this.balance;
	}

	public void setBalance(Double balance) {
		this.balance = balance;
	}

}
